// <auto-generated />
using System;
using AudioGuide.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace AudioGuide.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001100725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioGuide.Core.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<double>("TriggerRadiusMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Pois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DINH_DOC_LAP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.6953 10.777)"),
                            TriggerRadiusMeters = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "NHA_THO_DUC_BA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.699 10.7798)"),
                            TriggerRadiusMeters = 15.0
                        },
                        new
                        {
                            Id = 3,
                            Code = "BUU_DIEN_TRUNG_TAM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.6999 10.7799)"),
                            TriggerRadiusMeters = 15.0
                        });
                });

            modelBuilder.Entity("AudioGuide.Core.Entities.PoiTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PoiId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("PoiTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "https://cdn.example.com/audio/vi/dinh_doc_lap.mp3",
                            Description = "Di tích lịch sử quốc gia đặc biệt, biểu tượng của sự thống nhất đất nước.",
                            DurationSeconds = 180,
                            LanguageCode = "vi",
                            PoiId = 1,
                            Title = "Dinh Độc Lập"
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "https://cdn.example.com/audio/en/dinh_doc_lap.mp3",
                            Description = "A special national historical relic and architectural landmark in District 1.",
                            DurationSeconds = 175,
                            LanguageCode = "en",
                            PoiId = 1,
                            Title = "Independence Palace"
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "https://cdn.example.com/audio/vi/nha_tho_duc_ba.mp3",
                            Description = "Kiệt tác kiến trúc cổ kính phong cách Roman và Gothic nằm giữa trung tâm Sài Gòn.",
                            DurationSeconds = 150,
                            LanguageCode = "vi",
                            PoiId = 2,
                            Title = "Nhà thờ Đức Bà Sài Gòn"
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "https://cdn.example.com/audio/en/nha_tho_duc_ba.mp3",
                            Description = "An iconic cathedral built during the French colonial period.",
                            DurationSeconds = 145,
                            LanguageCode = "en",
                            PoiId = 2,
                            Title = "Notre-Dame Cathedral Basilica of Saigon"
                        },
                        new
                        {
                            Id = 5,
                            AudioUrl = "https://cdn.example.com/audio/vi/buu_dien_trung_tam.mp3",
                            Description = "Công trình kiến trúc mang đậm dấu ấn phong cách Pháp được khánh thành vào cuối thế kỷ 19.",
                            DurationSeconds = 120,
                            LanguageCode = "vi",
                            PoiId = 3,
                            Title = "Bưu điện Trung tâm Thành phố"
                        },
                        new
                        {
                            Id = 6,
                            AudioUrl = "https://cdn.example.com/audio/en/buu_dien_trung_tam.mp3",
                            Description = "One of the oldest and most beautiful post offices in Southeast Asia.",
                            DurationSeconds = 115,
                            LanguageCode = "en",
                            PoiId = 3,
                            Title = "Saigon Central Post Office"
                        });
                });

            modelBuilder.Entity("AudioGuide.Core.Entities.QrCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PoiId")
                        .HasColumnType("int");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("QrCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PoiId = 1,
                            QrToken = "qr-ddl-01",
                            ScanCount = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PoiId = 2,
                            QrToken = "qr-ntdb-02",
                            ScanCount = 0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PoiId = 3,
                            QrToken = "qr-bdsg-03",
                            ScanCount = 0
                        });
                });

            modelBuilder.Entity("AudioGuide.Core.Entities.PoiTranslation", b =>
                {
                    b.HasOne("AudioGuide.Core.Entities.Poi", "Poi")
                        .WithMany("Translations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AudioGuide.Core.Entities.QrCode", b =>
                {
                    b.HasOne("AudioGuide.Core.Entities.Poi", "Poi")
                        .WithMany("QrCodes")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AudioGuide.Core.Entities.Poi", b =>
                {
                    b.Navigation("QrCodes");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
